---
# tasks file for munin_resource_per_process

- block:

    - name: Create {{munin_resource_pp_target_dir}} if needed
      file:
        path: "{{munin_resource_pp_target_dir}}"
        state: directory
        mode: 0755
    
    - name: Create plugin(s) in {{munin_resource_pp_target_dir}}
      template:
        src: "plugin_template.j2"
        dest: "{{munin_resource_pp_target_dir}}/{{item.plugin_name}}"
        mode: 0755
        backup: yes
      notify : restart munin-node
      with_items: '{{munin_resource_pp_resources}}'
    
    - name: Enable (symlink) custom plugin(s)
      file:
        src: "{{munin_resource_pp_target_dir}}/{{item.plugin_name}}"
        dest: '/etc/munin/plugins/{{item.plugin_name}}'
        state: link
      notify : restart munin-node
      with_items: '{{munin_resource_pp_resources}}'

  become: True
